### ISSUE TITLE
Default wireless config

### ISSUE THREAD

**Issue by brunnels** [JiapengLi/OpenWrt-HiLink-HLK-RM04#10]
I have only the module so I can only connect to the device via serial or wifi.  Before I flash OpenWRT I want to ask if there is a default wireless AP mode configured or default serial tty configured?

**Comment by Skeen** [comment]
WIFI is disabled by default, and must be enabled in configuration files.
You can usually access the module via. ethernet (initial over telnet, then ssh) or via. serial.
- I do believe this is module dependent however.

**Comment by JiapengLi** [comment]
Totally agree with Skeen! Thank you!
