### ISSUE TITLE
Issue with OpenWrt compillation

### ISSUE THREAD

**Issue by maxencechotard** [JiapengLi/OpenWrt-HiLink-HLK-RM04#11]
I am working on the implementation of openwrt on a HLK-RM04 for a project and I am facing problems when I am following this tutorial to compile. When I try to compile using make, I get this error : 

gcc -O2 -I/home/xsoen/Documents/Developpement/openwrt/trunk/staging_dir/host/include -include endian.h  -o /home/xsoen/Documents/Developpement/openwrt/trunk/build_dir/host/firmware-utils/bin/mkhilinkfw src/mkhilinkfw.c  -lcrypto
src/mkhilinkfw.c:28:25: fatal error: openssl/des.h: No such file or directory
# include <openssl/des.h>

Do you have any idea about where the problem come from ?

**Comment by jkent** [comment]
Hi maxencechotard,

Do you have the development package of openssl installed?  (on deb based systems this would be `libssl-dev` -- it may be the same on rpm systems)

**Comment by maxencechotard** [comment]
Hi jkent,
Thank you for your help, it solved my problem.
