### ISSUE TITLE
Problem to compile sysupgrade.bin

### ISSUE THREAD

**Issue by maxencechotard** [JiapengLi/OpenWrt-HiLink-HLK-RM04#12]
When I am compiling openwrt for HLK-RM04 I can't get openwrt-ramips-rt305x-hlk-rm04-squashfs-sysugrade.bin file. I succeeded once to get it but after adding new packages to my build I can't get it anymore. Is there a way to specify that I want sysupgrade.bin file when I make menuconfig ? Thank you for your help !

**Comment by JiapengLi** [comment]
I am not sure what is your issue. I just compiled openwrt-trunk@45483, I got the sysupgrade.bin with default configuration. I am not sure if you select too many packages make the firmware out of space.

**Comment by maxencechotard** [comment]
Yes, I think I was out of memory, thank you for your answer.
