### ISSUE TITLE
openwrt-hlk-rm04-firwmware-tool.patch patch failed

### ISSUE THREAD

**Issue by winterland1989** [JiapengLi/OpenWrt-HiLink-HLK-RM04#2]
When i'm try to patch the makefile, the firwmware-tool patch failed, i checked the file and the correct patch should be this:

``` c++
@@ -65,6 +65,7 @@
         $(call cc,fix-u-media-header cyg_crc32,-Wall)
         $(call cc,hcsmakeimage bcmalgo)
         $(call cc,mkporayfw, -Wall)
+        $(call cc,mkhilinkfw, -lcrypto)
+        $(call cc,mkdcs932, -Wall)
```

**Comment by JiapengLi** [comment]
Which revision of trunk did you use?  Please checkout the r38317 or revision later. Because the Makefile which need to patch is updated. See this:
https://dev.openwrt.org/browser/trunk/tools/firmware-utils/Makefile

**Comment by JiapengLi** [comment]
@winterland1989  
I have updated the readme. Thank you!

**Comment by winterland1989** [comment]
Yeah~ that i'm talking about, the trunk's makefile of new version already have $(call cc,mkdcs932, -Wall), so the patch works now, for r38317, i just use add that line for a workaround
