### ISSUE TITLE
Can't find LuCI --> Collections --> luci

### ISSUE THREAD

**Issue by acrobotic** [JiapengLi/OpenWrt-HiLink-HLK-RM04#4]
I'm following the instructions on the README and I couldn't find the LuCI sub-menu.  Any chance you could point me in the right direction?

**Comment by JiapengLi** [comment]
Did you run the commands:

```
./scripts/feeds update -a
./scripts/feeds install -a
```

Or you may try these commands altogether

```
rm -rf .config tmp
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig
```

**Comment by acrobotic** [comment]
I thought I did on my first attempt, but for whatever reason it hadn't pulled LuCI, thanks for the help!
